### ISSUE TITLE
Code Review #1

### ISSUE THREAD

**Issue by MaikuDev** [haikustudio/haiku-coding-club#1]
### Errores de dedo

- Las etiquetas que no cuentan con contenido (children) deben cerrarse en la misma linea...
` <Tab heading="All" />`
https://github.com/haikustudio/haiku-coding-club/blob/5ded40fabc97cb0caa4d90284be28741261147a3/Doist/src/containers/Home/index.js#L24-L25

- Recuerda que los estilos deben ir en otro archivo, a veces si es necesario declarar algunos en `index.js`...
https://github.com/haikustudio/haiku-coding-club/blob/5ded40fabc97cb0caa4d90284be28741261147a3/Doist/src/containers/Home/index.js#L32

- Si se llegara a necesitar dar un salto de linea a las propiedades de una etiqueta, para darle una mejor estética al código y sea mas entendible, dichos salto se le debe aplicar a todas las propiedades...
```
<Image 
    source={{uri: 'https://s3.amazonaws.com/uifaces/faces/twitter/whale/128.jpg'}}
    style={{width: 160, height: 160, borderRadius: 100}} /> // a mi me gusta dejar el cierre de etiqueta arriba
 
//OR

<Image 
    source={{uri: 'https://s3.amazonaws.com/uifaces/faces/twitter/whale/128.jpg'}}
    style={{width: 160, height: 160, borderRadius: 100}} 
/> // En los guidelines de airbnb recomiendan bajar el cierre de etiqueta
```
https://github.com/haikustudio/haiku-coding-club/blob/5ded40fabc97cb0caa4d90284be28741261147a3/Doist/src/containers/Doist/index.js#L17-L18

- Recuerda la indentación...
```
<Button
    title="TWITTER"
    color="#757575"
/>
```
https://github.com/haikustudio/haiku-coding-club/blob/5ded40fabc97cb0caa4d90284be28741261147a3/Doist/src/containers/Doist/index.js#L33-L36

Sugerencias

- Te sugiero que las propiedades estáticas de la navegación las declares en el mismo lugar donde declaras tu stack 
```
const StartStack = createStackNavigator({
  Doist: {
    screen: Doist,
    navigationOptions: {
        header: null
    }
  }
})
```
https://github.com/haikustudio/haiku-coding-club/blob/5ded40fabc97cb0caa4d90284be28741261147a3/Doist/src/containers/Doist/index.js#L9-L11

- Te recomiendo exportar las clases de la siguiente manera
```
class Home extends Component<Props> {...}
module.exports = Home
```
https://github.com/haikustudio/haiku-coding-club/blob/5ded40fabc97cb0caa4d90284be28741261147a3/Doist/src/containers/Home/index.js#L12

**Comment by gowtski** [comment]
Hola, @MaikuDev gracias por el review 💯 

Respecto a los errores:
* El componente `<Tab>` es propio de la biblioteca de NativeBase, la cual se dejó así para ponerle contenido al Switch.
* Los estilos que se integraron directamente en la etiqueta son ejemplo de que también se pueden poner ahí si son pocos, o en el propio `index.js` declarando una constante.

Respecto a las sugerencias: 
* ¿En qué sería diferente si se exporta una clase como recomiendas?
En lo personal hago lo siguiente:

```
class Home extends Component<props> { ... }

export default Home
```

**Comment by Paueight** [comment]
Hola @MaikuDev @gowtski 
Ya arregle los errores sobre indentación y saltos de línea. 
Sobre las demás observaciones en cuanto Migue lea el comentario de Ari, me dicen si realizo los cambios que faltan :)

**Comment by MaikuDev** [comment]
Hola @gowtski @Paueight 

- Respecto a la pregunta del `export`, en si no tendría diferencia en el uso, como `export default Home` y `module.exports = Home` en teoria seria lo mismo, creo que la mejor opción podría ser `export default`...

```
class Home extends Component<props> { ... }
export default Home
```
porque es de ES6 y el otro ES5

- Respecto a los errores, ya no tengo ningún inconveniente, lo que en entendí es que las `Tabs` tendrán un contenido en el futuro y los estilos mencionados son solo ejemplos

**Comment by Paueight** [comment]
Bueno @gowtski @MaikuDev si hay otro error que corregir me lo hacen saber :)
