### ISSUE TITLE
Code Review #2

### ISSUE THREAD

**Issue by MaikuDev** [haikustudio/haiku-coding-club#2]
Parece que todo va bien solo son algunos detalles que pude ver..

* Los `;` en js ya no es necesario que los pongas y por guidelines no hay que ponerlas 
* Ari y yo descubrimos que no es necesario usar por el momento `type Props = {};`de igual manera podrías removerlo 
* Sigo con la recomendación para que el código se vea mas estético que uses el siguiente método para exportar las clases...

```
class Home extends Component<props> { ... }
export default Home
```

**Comment by Paueight** [comment]
Gracias por las observaciones @MaikuDev :D
